### ISSUE TITLE
Duration is not displayed in search results

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#21] opened 2019-05-29 08:01 UTC
From @B3N4K: https://github.com/mopidy/mopidy-youtube/issues/103#issuecomment-496816092

When i use `api_enabled = false`, duration is not displayed in search results.

**Comment by natumbri** [comment] 2019-05-29 08:01
What mopidy client are you using? My client doesn't show duration, so I've never noticed this.

**Comment by B3N4K** [comment] 2019-05-29 08:15
I'm using both [Iris](https://github.com/jaedb/Iris) and [Party](https://github.com/Lesterpig/mopidy-party) web clients - both displaying the duration and both have it missing for YT videos.

But I've found the culprit finally - it's in `backend.py`:

```
def search(self, query=None, uris=None, exact=False):

        ....

        tracks.append(Track(
                name=entry.title.get().replace(';', ''),
                comment=entry.id,
                length=0,

        ....

```

should be

```
def search(self, query=None, uris=None, exact=False):

        ....

        tracks.append(Track(
                name=entry.title.get().replace(';', ''),
                comment=entry.id,
                length=int(entry.length.get())*1000,

        ....

```

Unfortunately i do not have github setup on my computer so i am currently unable to create a PR. Sorry about that.

**Comment by natumbri** [comment] 2019-05-29 08:21
Thanks! I think that was something that I was going to get around to but
never did. Can't remember why it was set to 0.

Don't worry about a PR, I'll sort it out.

Cheers

**Comment by B3N4K** [comment] 2019-05-29 08:24
Wonderful, thanks a lot!

**Comment by natumbri** [comment] 2019-05-29 12:23
Ok - I think it is fixed.  @B3N4K let me know if it is working for you...

**Comment by B3N4K** [comment] 2019-05-29 16:52
Yep, can confirm, the issue is resolved with the latest commits in the `feature/proxy` branch. Thanks a lot!

**Closed** 2019-05-29 21:06 UTC
Labels: bug
