### ISSUE TITLE
GStreamer error: Forbidden when playing youtube video

### ISSUE THREAD

**Issue by jaminh** [natumbri/mopidy-youtube#134] opened 2020-02-27 14:21 UTC
I have noticed when trying to play youtube videos that I had previously played the previous day I would start getting a "GStreamer error: Forbidden". I suspect this is because the youtube plugin is caching the streaming URL when the video is first looked up, but that URL becomes invalid after some time.

**Comment by kingosticks** [comment] 2020-02-27 14:30
Even with your fix, what happens if you start playing, pause the song, wait a long time, then resume playback? And also when the song is really long (hours)? Mopidy-Gmusic suffers from both these issues due to the URI expiring.

**Comment by jaminh** [comment] 2020-02-28 14:05
It's possible we might be able to get around the issues you pointed out using something like GStreamer's download buffering? I'm pretty new to this but the description here makes it sound like it could work https://gstreamer.freedesktop.org/documentation/application-development/advanced/buffering.html?gi-language=c#download-buffering. But whether that works or not the cache in the youtube plugin would still be an issue when playing a previously played track. I still think it makes sense to include these changes and then open a separate issue for the other issue you brought up.

**Comment by natumbri** [comment] 2020-02-29 02:13
Thanks @jaminh and @kingosticks - I have wondered about how useful the cache in the YouTube extension is at all, in typical use. Maybe it is just an unnecessary complication?

Regarding the other thing, is there any way in the mopidy environment to give a URI a lifetime? And then, whenever an action is taken using the URI (play, resume playing, keep playing), to check whether the lifetime has been exceeded (and if so, grab a new URI)?

**Comment by kingosticks** [comment] 2020-02-29 08:23
You could always re-lookup the uri just before you start playing a track in translate_uri. Problem is that once playing, gstreamer doesn't let you modify the uri without effectively changing tracks. So if the uri expires once you start playing you are still stuffed. The best place to handle that would be within the gstreamer element itself. 

Or, as I experimented with for Mopidy-gmusic once upon a time , a proxy layer that hides the real uri from gstreamer. But that didn't work in environments where people were already using a network proxy.

Having gstreamer buffer the entire song is one solution which there was (is?) a Mopidy PR for. But the memory requirements for very long tracks (hours) get a bit out of hand and there didn't seem to be a way to control that.

**Comment by natumbri** [comment] 2020-04-18 05:08
Argh.  I've mucked something up, by running mopidy as sudo, instead of as the service.  

I now get
```
2020-04-18 14:57:22,467 ERROR [13693:MainThread] mopidy.audio.gst: GStreamer error: Forbidden
```
for some files when running as a service.  Everything works fine when running as sudo.  LRU v TTL doesn't make any difference.

I assume that either mopidy or tornado or youtube-dl or gstreamer or something else has made a file, or modified the permissions of an existing file, when running as sudo such that the file can't be accessed (or overwritten) my mopidy when it is running as a service (as user ```mopidy```).  Very frustrating!

**Comment by natumbri** [comment] 2020-04-27 11:39
youtube-dl caches some things (in ```/var/lib/mopidy/.cache```) that seem to muck playback up - passing ```"cachedir": False``` to YoutubeDL _seems_ to have fixed it.

**Comment by asdf123101** [comment] 2020-10-24 00:03
I'm also having the exact same issue, running mopidy as a service. The URL of the youtube video is valid. Mopidy can play the video after restarting the service. I have to restart mopidy every few hours to keep it working at the moment. 'cachedir: False' doesn't help in my case. The latest code comes with this flag.

**Comment by natumbri** [comment] 2020-10-24 00:29
Could you try this branch: https://github.com/natumbri/mopidy-youtube/tree/feature/download-buffering

Probably will not help, but worth a try...?

NB. download-buffering relies on a feature of mopidy that has been merged into the github `develop` branch, but has not yet been released.  It looks like it will be included in mopidy 3.1, when that is released.  Until then, if you want to test this fix, you'll need to be running a version of mopidy from`develop` on github.

**Comment by kingosticks** [comment] 2020-10-24 07:43
Now, this is a good example of what download buffering can help with!  Although it does stil have the memory issues we talked about before. Maybe they are not noticeable in practice.

**Comment by asdf123101** [comment] 2020-10-25 20:28
> Could you try this branch: https://github.com/natumbri/mopidy-youtube/tree/feature/download-buffering
> 
> Probably will not help, but worth a try...?
> 
> NB. download-buffering relies on a feature of mopidy that has been merged into the github `develop` branch, but has not yet been released. It looks like it will be included in mopidy 3.1, when that is released. Until then, if you want to test this fix, you'll need to be running a version of mopidy from`develop` on github.

I installed the new package from that branch but It didn't help. Still got the same error: `GStreamer error: Forbidden`.

**Comment by kingosticks** [comment] 2020-10-25 21:36
Can you provide a debug log?

**Comment by asdf123101** [comment] 2020-10-25 21:56
I'll reproduce the issue with with debug log on. Will report back when I have detailed log related to the error.
What I have at the moment is not very informative:
```
Oct 25 16:20:51 mopidy[3142758]: INFO     2020-10-25 16:20:51,960 [3142758:YouTubeBackend-6] mopidy_youtube
Oct 25 16:20:51 mopidy[3142758]:   youtube PlaybackProvider.translate_uri "youtube:video/video-name"
Oct 25 16:20:52 mopidy[3142758]: ERROR    2020-10-25 16:20:52,021 [3142758:MainThread] mopidy.audio.gst
Oct 25 16:20:52 mopidy[3142758]:   GStreamer error: Forbidden
```

**Comment by asdf123101** [comment] 2020-10-27 17:39
Here's what I got today. Looks like the URL it tried to play expired. But how come the same track can be played after restarting mopidy? Does it have something to do with how mopidy-youtube calls youtube-dl?
```
Oct 27 13:23:25 mopidy[4017904]:   Iris websocket message received: {"jsonrpc":"2.0","id":160381940562287,"method":"broadcast","params":{"method":"notification","params":{"notification":{"content":"asdf123101 changed track"}}}}
Oct 27 13:23:25 mopidy[4017904]: DEBUG    2020-10-27 13:23:25,626 [4017904:HttpServer] mopidy_iris.core
Oct 27 13:23:25 mopidy[4017904]:   {'method': 'notification', 'params': {'notification': {'content': 'asdf123101 changed track'}}, 'connection_id': '36D6NP33MWPX'}
Oct 27 13:23:25 mopidy[4017904]: DEBUG    2020-10-27 13:23:25,626 [4017904:HttpServer] mopidy_iris.core
Oct 27 13:23:25 mopidy[4017904]:   {'id': 160381940562287, 'jsonrpc': '2.0', 'method': 'broadcast', 'result': {'message': 'Broadcast to 1 connections'}, 'recipient': '36D6NP33MWPX'}
Oct 27 13:23:25 mopidy[4017904]: ERROR    2020-10-27 13:23:25,840 [4017904:MainThread] mopidy.audio.gst
Oct 27 13:23:25 mopidy[4017904]:   GStreamer error: Forbidden
Oct 27 13:23:25 mopidy[4017904]: DEBUG    2020-10-27 13:23:25,841 [4017904:MainThread] mopidy.audio.gst
Oct 27 13:23:25 mopidy[4017904]:   Got ERROR bus message: error=GLib.Error('Forbidden', 'gst-resource-error-quark', 15) debug='../gst-plugins-good/ext/soup/gstsouphttpsrc.c(1436): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin1/GstSoupHTTPSrc:source:\nForbidden (403), URL: https://manifest.googlevideo.com/api/manifest/dash/expire/1603779897/ei/2GiXX8byOKqJ2_gP0MKqgAM/ip/174.92.80.8/id/948da0b3c8941b28/source/youtube/requiressl/yes/playback_host/r8---sn-cxaaj5o5q5-tt1e6.googlevideo.com/mh/Mk/mm/31%2C26/mn/sn-cxaaj5o5q5-tt1e6%2Csn-vgqsknel/ms/au%2Conr/mv/m/mvi/8/pl/22/tx/23951660/txs/23951655%2C23951656%2C23951657%2C23951658%2C23951659%2C23951660%2C23951661/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/gcr/ca/initcwndbps/1671250/vprv/1/mt/1603758161/fvip/5/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cgcr%2Cvprv%2Citag/sig/AOq0QJ8wRQIgCNnPF0kmoeDeRvmFNXXjTbQ8DrtiZ_odUVI0LBUPyKoCIQCFhpYP5Qdn5Ubi99gLrQFWwXjZUy4OlKemdRhaayN8zA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAMnB6p3Ox-cG6anxBCGm__gfuaR8xmXY6l4Pl8ZYvAJ7AiEAzU1b6raDvKJ6N0H_l5w98X8ICsDxDSlWqENp_i2bQJw%3D, Redirect to: (NULL)'
Oct 27 13:23:25 mopidy[4017904]: DEBUG    2020-10-27 13:23:25,845 [4017904:MainThread] mopidy.audio.gst
Oct 27 13:23:25 mopidy[4017904]:   Changing state to GST_STATE_NULL: result=GST_STATE_CHANGE_SUCCESS
```

**Comment by natumbri** [comment] 2020-10-27 23:34
What if we don't load the video url until it is played, instead of loading it when it is searched (see https://github.com/natumbri/mopidy-youtube/compare/fix/issue-134, and try that branch)?

**Comment by asdf123101** [comment] 2020-10-29 19:02
Looks like the error is gone but the track is still unplayable:
```
DEBUG    2020-10-29 14:57:38,934 [882437:Audio-2] mopidy.audio.actor
Track is not playable: youtube:video/- I will... THE FIRST TAKE.1R5jREc_joY
Position query failed
```
The link to the track is valid: https://www.youtube.com/watch?v=1R5jREc_joY.
I guess we are making some progress here...

**Comment by l3d00m** [comment] 2020-11-17 11:09
For me it just happened again with the newest development version (freshly installed yesterday with `python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip`):

```
Nov 17 12:04:44 raspi4 mopidy[21062]: INFO     2020-11-17 12:04:44,835 [21062:YouTubeBackend-3] mopidy_youtube
Nov 17 12:04:44 raspi4 mopidy[21062]:   youtube PlaybackProvider.translate_uri "youtube:video/Stephan Bodzin live Piz Gloria in Murren Switzerland for Cercle.xF_QkfZI1mM"
Nov 17 12:04:45 raspi4 mopidy[21062]: ERROR    2020-11-17 12:04:45,090 [21062:MainThread] mopidy.audio.gst
Nov 17 12:04:45 raspi4 mopidy[21062]:   GStreamer error: Forbidden
```

I loaded the tracks yesterday evening, paused the playback and resumed this morning. It worked for a few minutes of that video and then suddenly stopped.

Edit: Sorry, I rushed this report in the morning and only skimmed the other comments so I oversaw the branch with the fix. I've installed now via `sudo pip3 install git+https://github.com/natumbri/mopidy-youtube.git@fix/issue-134` and report back if that's fixed. Thanks for maintaining this so actively!

**Comment by pipip** [comment] 2021-01-25 21:49
I installed @fix/issue-134 and still have the issue

**Comment by pipip** [comment] 2021-02-05 21:04
I installed @fix/issue-134 and don't have the issue anymore. thanks

**Comment by natumbri** [comment] 2021-02-27 04:07
fix/issue-134 was merged. Assume this can be closed.

**Closed by natumbri** 2021-02-27 04:07 UTC

**Comment by fsquillace** [comment] 2021-04-03 13:39
Hi, I've got the same issue in the latest release (3.2). I guess this has not been merged into mainline and released right?

Thanks for maintaining this plugin. It is simply the best!

**Comment by ned-kelly** [comment] 2021-04-12 03:12
> Hi, I've got the same issue in the latest release (3.2). I guess this has not been merged into mainline and released right?
> 
> Thanks for maintaining this plugin. It is simply the best!

+1

**Comment by natumbri** [comment] 2021-04-12 04:56
v3.3 now has `ttlcache` - any improvement?

**Comment by ned-kelly** [comment] 2021-04-12 04:58
~~Is 3.3 on Pypi yet, or build/pull from github?~~
Will test and update / post back....

**Comment by ned-kelly** [comment] 2021-04-12 12:54
Nope, still happening on 3.3 ... Is it worth adding `ttlcache` as an environment variable perhaps?

Works for about 1 hour for me (if I load a youtube playlist with say 50 songs it gets about half way through before it starts...)

**Comment by natumbri** [comment] 2021-04-12 17:41
@ned-kelly are you able to manually edit `cache_ttl = ` in `youtube.py` and set it to something small, say 600?

**Comment by ned-kelly** [comment] 2021-04-13 10:28
I'll change and see as I do want to try and fix this long term ... I ended up just making a program that checks if the playback state is "playing" but the time is not elapsed and just removing the playlist then re-adding it...

**Comment by dualfade** [comment] 2021-11-07 04:22
@natumbri confirmed works. Nice. Thanks !
