### ISSUE TITLE
Can't play Youtube song

### ISSUE THREAD

**Issue by PJkeeh** [natumbri/mopidy-youtube#68] opened 2016-07-27 14:04 UTC
I get this error message

```
INFO     Need 11 character video id or the URL of the video. Got //youtube:video/kidd funkadelic - maggot brain.3aAzdHnYfuk
ERROR    YoutubeBackend backend returned bad data: Expected a list of Track, not [None]
```

**Comment by ginandtronic** [comment] 2016-10-26 15:41
Hey ive got the same issue........

**Comment by jcass77** [comment] 2016-10-26 17:44
This might be related to #70.

What happens if you install youtube-dl with ``pip install youtube-dl`` and try again?

**Comment by ginandtronic** [comment] 2016-10-26 20:57
Thanks @jcass77 but im still getting this error...im sure it was playing youtube videos 2-3 days ago.. 

INFO     Need 11 character video id or the URL of the video. Got //youtube:video/Taco - Puttin on the Ritz (Original Uncensored Version).OG3PnQ3tgzY
ERROR    YoutubeBackend backend returned bad data: Expected a list of Track, not [None]

**Comment by arunpyasi** [comment] 2016-10-28 15:01
Yes, I also got the same error and was working few days before. Please fix this issue ASAP.
Thanks !

**Comment by mczerski** [comment] 2016-11-06 23:58
I have the same problem, but i can play song @PJkeeh posted and cannot play the one @ginandtronic posted.
also i have different error:
WARNING  Track is not playable: youtube:video/Taco - Puttin on the Ritz (Original Uncensored Version).OG3PnQ3tgzY
i'm using 2.0.0-2 (from apt) version

**Comment by mczerski** [comment] 2016-11-07 00:17
ok, i removed mopidy-youtube and pafy from the system then installed mopidy-youtube with pip (2.0.2 version) and the problem is gone :)

**Comment by alfaktulu** [comment] 2017-12-21 21:13
but this is dirty @mczerski , with this you can't search youtube's videos with mpc. I have installed youtube-dl with pip and can't play .OG3PnQ3tgzY (Taco's song) too. I use Mopidy on Orange Pi Zero with Armbian jessie.

**Comment by alfaktulu** [comment] 2017-12-21 21:32
and more I removed mopidy-youtube and I installed with pip 2.0.2 and then don't play this song .OG3PnQ3tgzY

**Comment by natumbri** [comment] 2020-01-13 05:16
OG3PnQ3tgzY has been removed from YouTube and Mopidy 3 / Mopidy-Youtube 3 plays 3aAzdHnYfuk, so closing this issue.

**Closed by natumbri** 2020-01-13 05:16 UTC
