### ISSUE TITLE
Now I can't load a playlist

### ISSUE THREAD

**Issue by alfaktulu** [natumbri/mopidy-youtube#91] opened 2018-03-10 01:37 UTC
I have a Orange Pi Zero, but now a I cant load any playlist. show me the next message, check this out:
"directory or file not found"
Before it did not happen!

**Comment by tfilo** [comment] 2018-03-10 08:47
Can you try mopidy local scan or if you run mopidy as service sudo mopidyctl local scan. If doesn't help. Try to show as your config: https://docs.mopidy.com/en/latest/troubleshooting/#show-effective-configuration
And permisions on directory yours files are in. ls -ls /path/to/directory

**Comment by kingosticks** [comment] 2018-03-10 09:08
Is this a specific mopidy-youtube problem or a local music problem? If the
latter please create a new post at discuss.mopidy.com.

Either way you just include the exact steps to reproduce the problem as
this report is not sufficient to help you effectively.

**Comment by Kunsi** [comment] 2018-03-18 16:16
Maybe related to the API key being invalid, should be fixed by #93

**Comment by eseca** [comment] 2018-03-24 23:41
Adding more info on the issue.
When adding a playlist:
```
$ mpc add yt:http://www.youtube.com/watch?list=RDMMNnFidFbwQSA
error adding yt:http://www.youtube.com/watch?list=RDMMNnFidFbwQSA: directory or file not found
```

This error is shown in the application log:
```
ERROR    YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 236, in lookup
    result = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 160, in lookup
    return resolve_playlist(req.get('list')[0])
  File "/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py", line 132, in resolve_playlist
    for item in data["items"]:
KeyError: u'items'
```
Debugged `/usr/lib/python2.7/site-packages/mopidy_youtube/backend.py:132` to find the content of `data`:
```
(Pdb) data
{u'error': {u'code': 403, u'message': u'Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'errors': [{u'domain': u'usageLimits', u'message': u'Access Not Configured. YouTube Data API has not been used in project 119103001349 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'reason': u'accessNotConfigured', u'extendedHelp': u'https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=119103001349'}]}}
```

**Comment by tfilo** [comment] 2018-03-25 06:51
This is related to other issue with API key. Since using youtube api for
this purpose is against google policy. They shutdown account with
registered API key. There is solution if you want to risk it. You can
generate your own api key on google developer site and change it in
backend.py file of mopidy youtube. But since it is against google policy.
They can shutdown your account too.

Dňa ne 25. 3. 2018, 0:41 Axel Becerril <notifications@github.com>
napísal(a):

**Comment by tfilo** [comment] 2018-03-25 06:55
Related issue  #87

**Closed** 2020-01-06 10:53 UTC
